//! A seeded library worth rendering.
//!
//! Every other tier here generates *import fixtures* — sidecars, CSV exports,
//! epubs. This one generates a **populated database**, because until it existed
//! every GUI thread started against an empty shelf or against a personal library
//! that cannot be committed, and neither of those renders anything worth looking
//! at.
//!
//! ## What it emits, and what it deliberately does not
//!
//! `seed.sql`, a pile of cover PNGs and a vault of markdown — and **not a
//! schema**. The engine owns the schema and `sqlx::migrate!` owns the ledger it
//! is recorded in (`_sqlx_migrations`, checksummed sha384 over each migration's
//! raw bytes). A generator that created tables would be a second copy of the
//! schema, free to drift; a generator that wrote the ledger would be a
//! reimplementation of sqlx's bookkeeping, and a wrong checksum there is a
//! `VersionMismatch` at startup rather than an obvious failure here. So
//! `make dev-db` has the real binary create and migrate an empty database, and
//! this file fills it.
//!
//! Everything is still `INSERT`s with **explicit column lists**, which is the
//! property that keeps the drift loud: rename a column and the seed fails at
//! `sqlite3` time naming it, instead of quietly leaving a NULL behind.
//!
//! ## The edge cases are the point
//!
//! The two hundred ordinary books are the backdrop. What this fixture is *for*
//! is the twenty-odd deliberate hostilities at the front of it — `page_count`
//! of zero (item 17b's false denominator), a 1,400-page doorstop beside a
//! 48-page pamphlet, no cover, a title long enough to need clipping, an RTL
//! title, a mononym author, a book with no author at all. They are the visual
//! regression suite, and they are also the exact inputs item 17's derived-facts
//! layer has to get right. `manifest.json` names each one so a screenshot
//! reviewer knows what it is looking for.
//!
//! This module, like the rest of the crate, does **not** depend on
//! `readingbuddy`.

use std::io::Write;
use std::path::{Path, PathBuf};

use rand_chacha::ChaCha8Rng;
use rand_core::{RngCore, SeedableRng};
use serde::Serialize;
use sha2::{Digest, Sha256};

const HEADER: &str = "\
-- GENERATED by `cargo run -p corpus -- gen-devdb`. Do not hand-edit.
--
-- Applied by `make dev-db` to a database the real binary has already created
-- and migrated. Every INSERT lists its columns, so a renamed column fails here
-- by name rather than leaving a silent NULL.
PRAGMA foreign_keys = ON;
BEGIN;
";

/// 2025-01-01 00:00:00 UTC. Fixed, never `now()` — a fixture whose timestamps
/// move is a fixture whose goldens move, and a screenshot taken from it would
/// differ every day for no reason.
const EPOCH: i64 = 1_735_689_600;
const DAY: i64 = 86_400;

/// Small enough that two hundred of them are a few hundred kilobytes, large
/// enough that a shelf tile is not visibly a thumbnail. Aspect is 2:3, the
/// ordinary trade paperback — item 20b will store the real thing per book, and
/// when it does this becomes the fallback rather than the truth.
const COVER_W: u32 = 240;
const COVER_H: u32 = 360;

/// `corpus/generated/devdb`, beside the tier-2 corpus and gitignored for the
/// same reason: it is large, it is reproducible from a seed, and a committed copy
/// would be a second source of truth for what the dev library contains.
pub fn default_out() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("corpus/generated/devdb")
}

/// `<repo>/dev-data` — the same default `make dev-db` uses for `DEV_DB_DIR`.
///
/// The generator needs it because `cover_path` is a **whole path** in this
/// schema (`Storage::set_cover` stores `images_dir.join(name)`), so the seed
/// cannot state one without knowing where the library will be built.
pub fn default_data_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("dev-data")
}

/// How many of the generated books are deliberate hostilities.
///
/// Exposed so the one line that reports it reads the number rather than
/// restating it. `make dev-db` printed a hand-written "220 books, 20 of them"
/// until item 38, which went stale the moment a case was added — a fixture
/// disagreeing with a claim about it, which is the whole subject of that item
/// arriving one line away from itself.
pub fn edge_case_count() -> usize {
    edge_cases().len()
}

pub fn generate(
    root: &Path,
    data_dir: &Path,
    seed: u64,
    ordinary: usize,
) -> std::io::Result<usize> {
    let covers = root.join("covers");
    let vault = root.join("vault");
    std::fs::create_dir_all(&covers)?;
    std::fs::create_dir_all(&vault)?;

    let mut rng = ChaCha8Rng::seed_from_u64(seed);
    let mut books: Vec<Book> = edge_cases();
    let edge_count = books.len();
    for i in 0..ordinary {
        books.push(ordinary_book(&mut rng, edge_count + i + 1));
    }
    for (i, b) in books.iter_mut().enumerate() {
        b.id = i as i64 + 1;
    }

    let mut sql = String::from(HEADER);
    let mut notes = Vec::new();
    let mut highlight_id = 0i64;
    let mut reading_id = 0i64;

    for b in &books {
        if b.cover {
            let name = format!("dev-{:04}.png", b.id);
            write_cover(&covers.join(&name), b.id)?;
        }
        sql.push_str(&b.insert(data_dir));
        for r in b.readings(&mut reading_id) {
            sql.push_str(&r);
        }
        for h in b.highlights(&mut highlight_id, &mut rng) {
            sql.push_str(&h);
        }
        for t in &b.tags {
            sql.push_str(&format!(
                "INSERT INTO book_tags (book_id, tag, source, raw) VALUES ({}, {}, 'goodreads', {});\n",
                b.id,
                q(&t.to_lowercase()),
                q(t)
            ));
        }
        if b.note {
            notes.push(b.clone());
        }
    }

    // Notes last, so their ids are contiguous and the link pass below can name
    // them without a second bookkeeping pass.
    for (i, b) in notes.iter().enumerate() {
        let note_id = i as i64 + 1;
        let slug = format!("{:04}-{}", note_id, slug(&b.title));
        let path = format!("{slug}.md");
        let title = format!("On {}", display_title(&b.title));
        // A dangling link on every third note. `note_links.to_note` is nullable
        // precisely so an unresolved target survives as text, and the links pane
        // (item 27) has to render both kinds — so both kinds have to exist here.
        let dangling = note_id % 3 == 0;
        let body = format!(
            "# {title}\n\n\
             A note against *{}*.\n\n\
             It links to [[{}]]{}\n",
            display_title(&b.title),
            if dangling {
                "A Note Nobody Wrote".to_string()
            } else {
                format!("On {}", display_title(&notes[0].title))
            },
            if dangling {
                " — deliberately unresolved."
            } else {
                "."
            }
        );
        std::fs::write(vault.join(&path), &body)?;

        let created = EPOCH + note_id * DAY;
        sql.push_str(&format!(
            "INSERT INTO notes (id, book_id, highlight_id, file_path, title, kind, created_at, last_modified) \
             VALUES ({note_id}, {}, NULL, {}, {}, 'note', {created}, {created});\n",
            b.id,
            q(&path),
            q(&title)
        ));
        // The engine writes `notes_fts` from application code — there is no
        // trigger on the table. A seeded note that skipped this row would be a
        // note `SearchNotes` cannot find, which is the one thing item 27's
        // search box exists to do.
        sql.push_str(&format!(
            "INSERT INTO notes_fts (rowid, title, body) VALUES ({note_id}, {}, {});\n",
            q(&title),
            q(&body)
        ));
        let target = if dangling {
            "A Note Nobody Wrote".to_string()
        } else {
            format!("On {}", display_title(&notes[0].title))
        };
        sql.push_str(&format!(
            "INSERT INTO note_links (from_note, to_note, target_title) VALUES ({note_id}, {}, {});\n",
            if dangling { "NULL".into() } else { "1".to_string() },
            q(&target)
        ));
    }

    sql.push_str("COMMIT;\n");
    std::fs::write(root.join("seed.sql"), &sql)?;

    let manifest = Manifest {
        generator_version: GENERATOR_VERSION,
        seed,
        books: books.len(),
        notes: notes.len(),
        edge_cases: books[..edge_count]
            .iter()
            .map(|b| EdgeCase {
                id: b.id,
                title: display_title(&b.title),
                what: b.why.to_string(),
            })
            .collect(),
    };
    let mut f = std::fs::File::create(root.join("manifest.json"))?;
    writeln!(
        f,
        "{}",
        serde_json::to_string_pretty(&manifest).expect("manifest is plain data")
    )?;

    Ok(books.len())
}

/// Bumped when the *shape* of what is emitted changes, so a stale `dev-data/`
/// is identifiable rather than mysterious. Same role as `gen-corpus`'s.
pub const GENERATOR_VERSION: u32 = 2;

#[derive(Serialize)]
struct Manifest {
    generator_version: u32,
    seed: u64,
    books: usize,
    notes: usize,
    edge_cases: Vec<EdgeCase>,
}

#[derive(Serialize)]
struct EdgeCase {
    id: i64,
    title: String,
    what: String,
}

#[derive(Clone)]
struct Book {
    id: i64,
    title: String,
    authors: Vec<String>,
    page_count: Option<i64>,
    cover: bool,
    isbn_13: Option<String>,
    series: Option<(String, Option<f64>)>,
    subjects: Vec<String>,
    tags: Vec<String>,
    state: State,
    highlights: usize,
    note: bool,
    /// Why this book is in the fixture. Empty for the ordinary two hundred;
    /// the edge cases each say what they are for, and it lands in the manifest.
    why: &'static str,
}

#[derive(Clone, Copy, PartialEq)]
enum State {
    /// No reading row at all — on the shelf, never opened. The commonest state
    /// in a real library and the one a "progress" column has no answer for.
    Unread,
    Reading,
    Finished,
    Abandoned,
    /// Two readings: one finished, one open. A reread mints a second card
    /// beside the first (item 28), so it must be possible to have two.
    Reread,
    /// A status word this build does not know, written straight into
    /// `readings.status`.
    ///
    /// `readings.status` has **no `CHECK` constraint** — the column comment in
    /// `0005_readings.sql` names three words and the schema permits any — so
    /// this is a state a real database can hold, not one invented for a
    /// fixture. It is how a newer importer's vocabulary arrives, and the engine
    /// answers it with `ReadingState::Other { raw }` rather than failing to
    /// parse. `fake.ts` has had this case since the scaffold and the real
    /// library had no counterpart, which is exactly the drift item 38 exists to
    /// make loud.
    Unknown,
}

impl Book {
    fn insert(&self, data_dir: &Path) -> String {
        let created = EPOCH + self.id * 137;
        let (series, index) = match &self.series {
            Some((s, i)) => (
                q(s),
                i.map(|v| format!("{v}")).unwrap_or_else(|| "NULL".into()),
            ),
            None => ("NULL".to_string(), "NULL".to_string()),
        };
        format!(
            "INSERT INTO books (id, title, sort_title, authors, translators, publisher, \
             publish_year, language, isbn_10, isbn_13, openlibrary_key, googlebooks_id, \
             cover_url, cover_path, page_count, description, first_sentence, \
             subjects, series, series_index, created_at, last_modified) VALUES \
             ({}, {}, NULL, {}, '[]', {}, {}, 'en', NULL, {}, NULL, NULL, NULL, {}, {}, {}, NULL, {}, {series}, {index}, {created}, {created});\n",
            self.id,
            q(&self.title),
            q(&json_array(&self.authors)),
            q("A Publisher"),
            1900 + (self.id % 125),
            self.isbn_13.as_deref().map(q).unwrap_or("NULL".into()),
            // A **whole path**, because that is what the schema holds:
            // `Storage::set_cover` stores `images_dir.join(name)` and nothing
            // downstream joins a prefix back on. This was relative for a wave,
            // on the argument that an absolute path names one machine — but this
            // seed is regenerated by `make dev-db` on the machine that runs it
            // and is gitignored, so the argument protected nothing and the cost
            // was real: a relative path resolves only from a process whose cwd
            // is the data dir, so `measure_stored_covers` read none of the 202
            // files, and a webview — which has no cwd at all — could resolve
            // none of them either.
            if self.cover {
                q(&data_dir
                    .join(format!("database/images/dev-{:04}.png", self.id))
                    .to_string_lossy())
            } else {
                "NULL".into()
            },
            self.page_count
                .map(|p| p.to_string())
                .unwrap_or("NULL".into()),
            q(&format!(
                "A description of {}, long enough to need wrapping in a detail pane but not \
                 long enough to be the only thing on it.",
                display_title(&self.title)
            )),
            q(&json_array(&self.subjects)),
        )
    }

    fn readings(&self, next: &mut i64) -> Vec<String> {
        let mut out = Vec::new();
        let mut push = |status: &str, started: i64, finished: Option<i64>, page: Option<i64>| {
            *next += 1;
            out.push(format!(
                "INSERT INTO readings (id, book_id, started_at, finished_at, status, source, \
                 current_page, ko_status, ko_percent, ko_rating, created_at, last_modified) VALUES \
                 ({}, {}, {started}, {}, '{status}', 'koreader', {}, NULL, {}, NULL, {started}, {started});\n",
                *next,
                self.id,
                finished.map(|f| f.to_string()).unwrap_or("NULL".into()),
                page.map(|p| p.to_string()).unwrap_or("NULL".into()),
                match (page, self.page_count) {
                    // Absence is not zero. A book with no page count has no
                    // percentage either — not 0.0, which every progress bar in
                    // the world would draw as a full-width empty track.
                    (Some(p), Some(total)) if total > 0 => format!("{:.4}", p as f64 / total as f64),
                    _ => "NULL".into(),
                }
            ));
        };
        let start = EPOCH + self.id * DAY;
        match self.state {
            State::Unread => {}
            State::Reading => push(
                "reading",
                start,
                None,
                Some(self.page_count.unwrap_or(0) / 3),
            ),
            State::Finished => push("finished", start, Some(start + 20 * DAY), self.page_count),
            State::Abandoned => push(
                "abandoned",
                start,
                Some(start + 9 * DAY),
                Some(self.page_count.unwrap_or(0) / 5),
            ),
            State::Reread => {
                push("finished", start, Some(start + 20 * DAY), self.page_count);
                push(
                    "reading",
                    start + 400 * DAY,
                    None,
                    Some(self.page_count.unwrap_or(0) / 2),
                );
            }
            // Open-shaped — no `finished_at` — because that is what makes it
            // reach `ReadingState::Other` rather than being read as a closed
            // reading with an odd label.
            State::Unknown => push(
                "paused",
                start,
                None,
                Some(self.page_count.unwrap_or(0) / 4),
            ),
        }
        out
    }

    fn highlights(&self, next: &mut i64, rng: &mut ChaCha8Rng) -> Vec<String> {
        (0..self.highlights)
            .map(|i| {
                *next += 1;
                let datetime = format!(
                    "2025-0{}-{:02} 1{}:0{}:00",
                    1 + i % 9,
                    1 + i % 27,
                    i % 10,
                    i % 6
                );
                let text = format!(
                    "{} — a passage from {}, of a length that has to wrap.",
                    PHRASES[(rng.next_u32() as usize) % PHRASES.len()],
                    display_title(&self.title)
                );
                let mut hasher = Sha256::new();
                hasher.update(format!("{}|{datetime}||{text}", self.id));
                // No `highlights_fts` row here, and that is the opposite of the
                // note above about `notes_fts` rather than an oversight.
                // Migration `0015` indexes highlights with triggers over an
                // external-content table, so this INSERT fills the index on its
                // way past — the seed is applied to an already-migrated
                // database. It is also the reason triggers were chosen: this
                // generator does not link the engine, so a hand-written Rust
                // writer would have had to be re-implemented right here.
                format!(
                    "INSERT INTO highlights (id, book_id, text, chapter, page, ko_datetime, color, \
                     ko_note, annotation, source, identity_hash, created_at) VALUES \
                     ({}, {}, {}, {}, {}, {}, 'yellow', {}, NULL, 'koreader', {}, {});\n",
                    *next,
                    self.id,
                    q(&text),
                    q(&format!("Chapter {}", 1 + i % 12)),
                    1 + (i as i64 * 17) % self.page_count.unwrap_or(300).max(1),
                    q(&datetime),
                    // A KOReader-attached note on every fourth one. The book view
                    // has to render a highlight with and without one.
                    if i % 4 == 0 {
                        q("What did they mean by this?")
                    } else {
                        "NULL".into()
                    },
                    q(&hex(&hasher.finalize())),
                    EPOCH + *next * 601
                )
            })
            .collect()
    }
}

/// The visual regression suite. Each one is a thing that has broken a real
/// reading app's shelf or detail pane, and each carries the sentence explaining
/// what to look at.
fn edge_cases() -> Vec<Book> {
    let base = |title: &str, why: &'static str| Book {
        id: 0,
        title: title.to_string(),
        authors: vec!["Ada Ordinary".into()],
        page_count: Some(300),
        cover: true,
        isbn_13: None,
        series: None,
        subjects: vec!["Fiction".into()],
        tags: vec![],
        state: State::Unread,
        highlights: 0,
        note: false,
        why,
    };
    vec![
        Book {
            page_count: Some(0),
            state: State::Reading,
            ..base(
                "A Book Of Zero Pages",
                "page_count = 0. Item 17b's false denominator: any percentage over this is a \
                 divide-by-zero, and the honest answer is that there is no percentage.",
            )
        },
        Book {
            page_count: None,
            state: State::Reading,
            ..base(
                "A Book Of Unknown Length",
                "page_count is NULL. Absence, not zero — a progress bar has nothing to draw and \
                 must not draw an empty one.",
            )
        },
        Book {
            page_count: Some(1408),
            state: State::Reading,
            highlights: 40,
            note: true,
            ..base(
                "The Doorstop",
                "1,408 pages. Item 19's thickness derivation has to make this visibly fatter than \
                 the pamphlet below it without leaving the shelf.",
            )
        },
        Book {
            page_count: Some(48),
            ..base(
                "A Pamphlet",
                "48 pages. The thin end of the same scale, and the case where a spine has no room \
                 for a title.",
            )
        },
        Book {
            cover: false,
            ..base(
                "A Book With No Cover At All",
                "cover_path is NULL. Not a broken image and not an apology — the empty state has \
                 to be a designed one.",
            )
        },
        Book {
            title: "A Title Of Such Considerable And Frankly Self-Indulgent Length That It Cannot \
                    Possibly Fit In A Shelf Tile Or A Column Header, Being In The Manner Of The \
                    Long Eighteenth Century, Wherein The Title Was Also The Blurb"
                .into(),
            ..base(
                "",
                "A 220-character title. Clipping, wrapping, and the tooltip that should carry the rest.",
            )
        },
        Book {
            authors: vec!["Borges, Jorge Luis".into()],
            ..base(
                "A Book Filed Under Surname",
                "Author stored as `Surname, Given` — the calibre and Goodreads form. Whether it is \
                 displayed that way is a derived fact and belongs to item 17, not to a Svelte \
                 template.",
            )
        },
        Book {
            authors: vec!["Colette".into()],
            ..base(
                "A Book By One Name",
                "A mononym author. Any name-splitting rule breaks here.",
            )
        },
        Book {
            authors: vec![],
            ..base(
                "A Book By Nobody",
                "No author at all. `authors` is `[]`, which is a real state after a bare epub \
                 import — not an error to report.",
            )
        },
        Book {
            authors: vec![
                "Ada Ordinary".into(),
                "Grace Second".into(),
                "Bea Third".into(),
            ],
            ..base(
                "A Book By Three People",
                "Three authors. Where the join and the truncation happen.",
            )
        },
        Book {
            state: State::Abandoned,
            highlights: 6,
            ..base(
                "A Book I Put Down",
                "An abandoned reading. Never styled as a failure — decisions.md says so by name.",
            )
        },
        Book {
            state: State::Reread,
            highlights: 12,
            note: true,
            ..base(
                "A Book I Went Back To",
                "Two readings, one finished and one open. Item 28's card is per reading, so this \
                 book has two of them.",
            )
        },
        Book {
            state: State::Finished,
            highlights: 22,
            note: true,
            isbn_13: Some("9780000000017".into()),
            ..base(
                "A Book I Finished",
                "A finished reading with highlights and a note.",
            )
        },
        Book {
            title: "北回帰線のあたりで".into(),
            authors: vec!["村上 春樹".into()],
            ..base(
                "",
                "CJK title and author. Font fallback, and character-count-based clipping being wrong.",
            )
        },
        Book {
            title: "الكتاب الذي يقرأ من اليمين".into(),
            authors: vec!["ابن خلدون".into()],
            ..base(
                "",
                "An RTL title. Bidi layout, and a left-aligned column that should not be.",
            )
        },
        Book {
            title: "Ærøskøbing: Ångström's Œuvre — a Naïve Façade".into(),
            ..base(
                "",
                "Diacritics and ligatures, including ones that break a naive sort.",
            )
        },
        Book {
            title: String::new(),
            ..base(
                "",
                "An empty title. The schema's own default, reachable from a sidecar with no doc_props.",
            )
        },
        Book {
            series: Some(("The Book Of The New Sun".into(), Some(2.0))),
            state: State::Reading,
            ..base(
                "The Claw Of The Conciliator",
                "A series with an index. `series_index` is a REAL and prints as `2`, not `2.0`.",
            )
        },
        Book {
            series: Some(("An Unnumbered Sequence".into(), None)),
            ..base(
                "A Book In A Series With No Number",
                "A series naming no index. The pair moves together or not at all.",
            )
        },
        Book {
            highlights: 1,
            note: true,
            subjects: vec![
                "Philosophy".into(),
                "Essays".into(),
                "Nineteenth century".into(),
            ],
            tags: vec!["Favourites".into(), "To reread".into()],
            state: State::Finished,
            ..base(
                "A Book With Subjects And Shelves",
                "Provider subjects beside minted shelves — two different things that look alike.",
            )
        },
        Book {
            state: State::Unknown,
            ..base(
                "A Book Some Other App Touched",
                "A reading whose status is a word this build does not know. `readings.status` has \
                 no CHECK constraint, so this is reachable; the engine answers it with \
                 `ReadingState::Other` rather than failing to parse.",
            )
        },
    ]
}

fn ordinary_book(rng: &mut ChaCha8Rng, n: usize) -> Book {
    let pick = |r: &mut ChaCha8Rng, xs: &[&str]| xs[(r.next_u32() as usize) % xs.len()].to_string();
    let title = format!("{} {}", pick(rng, ADJECTIVES), pick(rng, NOUNS));
    let author = format!("{} {}", pick(rng, GIVEN), pick(rng, FAMILY));
    let pages = 90 + (rng.next_u32() % 600) as i64;
    // Roughly a real shelf: most books unread, a handful open, a long tail
    // finished. Not a uniform draw — a shelf where a third of everything is
    // in progress does not look like anybody's library.
    let state = match rng.next_u32() % 100 {
        0..=57 => State::Unread,
        58..=64 => State::Reading,
        65..=68 => State::Abandoned,
        69..=71 => State::Reread,
        _ => State::Finished,
    };
    Book {
        id: 0,
        title,
        authors: vec![author],
        page_count: Some(pages),
        cover: !rng.next_u32().is_multiple_of(12),
        isbn_13: Some(format!("978{:010}", n)),
        series: None,
        subjects: vec![pick(rng, SUBJECTS)],
        tags: vec![],
        state,
        highlights: match state {
            State::Unread => 0,
            _ => (rng.next_u32() % 14) as usize,
        },
        note: rng.next_u32().is_multiple_of(5) && state != State::Unread,
        why: "",
    }
}

// ---- covers ---------------------------------------------------------------

/// A flat two-tone cover, deterministic from the book id.
///
/// Not a picture of anything — the point is that a shelf of two hundred of these
/// has two hundred *distinguishable* tiles, so a layout bug (every tile the same
/// image, tiles off by one, a tile that failed to load) is visible at a glance
/// rather than plausible.
fn write_cover(path: &Path, id: i64) -> std::io::Result<()> {
    // Golden-ratio hue stepping: consecutive ids are far apart in colour, which
    // is what makes an off-by-one in a grid obvious.
    let hue = ((id as f64) * 137.507_764_05) % 360.0;
    let (r, g, b) = hsv_rgb(hue, 0.45, 0.72);
    let (dr, dg, db) = hsv_rgb(hue, 0.60, 0.38);

    let mut data = Vec::with_capacity((COVER_W * COVER_H * 3) as usize);
    for y in 0..COVER_H {
        // A band across the upper third, so a vertically-flipped or
        // wrongly-cropped cover is not symmetric enough to hide it.
        let band = y > COVER_H / 5 && y < COVER_H / 3;
        for x in 0..COVER_W {
            let spine = x < COVER_W / 16;
            let (r, g, b) = if band || spine {
                (dr, dg, db)
            } else {
                (r, g, b)
            };
            data.extend_from_slice(&[r, g, b]);
        }
    }

    let file = std::fs::File::create(path)?;
    let mut enc = png::Encoder::new(std::io::BufWriter::new(file), COVER_W, COVER_H);
    enc.set_color(png::ColorType::Rgb);
    enc.set_depth(png::BitDepth::Eight);
    let mut w = enc
        .write_header()
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    w.write_image_data(&data)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    w.finish().map_err(|e| std::io::Error::other(e.to_string()))
}

fn hsv_rgb(h: f64, s: f64, v: f64) -> (u8, u8, u8) {
    let c = v * s;
    let hp = h / 60.0;
    let x = c * (1.0 - ((hp % 2.0) - 1.0).abs());
    let (r, g, b) = match hp as u32 {
        0 => (c, x, 0.0),
        1 => (x, c, 0.0),
        2 => (0.0, c, x),
        3 => (0.0, x, c),
        4 => (x, 0.0, c),
        _ => (c, 0.0, x),
    };
    let m = v - c;
    let f = |n: f64| ((n + m) * 255.0).round().clamp(0.0, 255.0) as u8;
    (f(r), f(g), f(b))
}

// ---- text helpers ---------------------------------------------------------

/// SQL single-quoted literal. The only escaping SQLite needs inside one is the
/// doubled quote; newlines are legal in a string literal, so a note body with
/// paragraphs travels whole.
fn q(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

fn json_array(xs: &[String]) -> String {
    let inner: Vec<String> = xs
        .iter()
        .map(|x| format!("\"{}\"", x.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect();
    format!("[{}]", inner.join(","))
}

/// What to call a book in prose the fixture itself writes. An empty title is a
/// real state, and "" reads as a bug in the generator rather than as the case
/// being exercised.
fn display_title(t: &str) -> String {
    if t.is_empty() {
        "an untitled book".to_string()
    } else {
        t.chars().take(48).collect()
    }
}

fn slug(t: &str) -> String {
    let s: String = t
        .to_lowercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    let s = s.trim_matches('-').to_string();
    let s: String = s.chars().take(40).collect();
    if s.is_empty() { "untitled".into() } else { s }
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

const ADJECTIVES: &[&str] = &[
    "The Pale",
    "A Brief",
    "The Long",
    "Silent",
    "The Last",
    "Northern",
    "The Glass",
    "Winter",
    "The Second",
    "Distant",
    "The Yellow",
    "Ordinary",
    "The Quiet",
    "Salt",
    "The Narrow",
    "Hollow",
];
const NOUNS: &[&str] = &[
    "King",
    "History",
    "Afternoon",
    "Country",
    "Machine",
    "Garden",
    "Letters",
    "Harvest",
    "Passage",
    "Inheritance",
    "Arithmetic",
    "Weather",
    "Cartographer",
    "Hours",
    "Bell",
    "Orchard",
];
const GIVEN: &[&str] = &[
    "Mariam", "Tobias", "Ines", "Fen", "Alasdair", "Yuki", "Nadia", "Owen", "Priya", "Casimir",
    "Ruth", "Emeka", "Solveig", "Bruno",
];
const FAMILY: &[&str] = &[
    "Achebe",
    "Bergman",
    "Cortez",
    "Dziedzic",
    "Eshun",
    "Fournier",
    "Grigorescu",
    "Halloran",
    "Iwasaki",
    "Jarrah",
    "Kowalski",
    "Lindqvist",
    "Mbeki",
    "Nakamura",
];
const SUBJECTS: &[&str] = &[
    "Fiction",
    "History",
    "Philosophy",
    "Poetry",
    "Science",
    "Biography",
    "Essays",
    "Travel",
];
const PHRASES: &[&str] = &[
    "The thing about a place is that it is still there when you are not",
    "He had the habit of arriving early and pretending otherwise",
    "Nothing in the record accounts for the missing fortnight",
    "It is a mistake to read a map as a promise",
    "She counted the bells and then stopped counting",
    "What survives is not what was meant to",
];

#[cfg(test)]
mod tests {
    use super::*;

    /// The declaration both fixtures answer to.
    ///
    /// Read as text and parsed, rather than `include!`d as Rust, because the
    /// other consumer is TypeScript: a shared declaration only shares anything
    /// if neither side owns its syntax.
    const DECLARED: &str = include_str!("../edge-cases.json");

    fn declared() -> Vec<serde_json::Value> {
        let v: serde_json::Value = serde_json::from_str(DECLARED).expect("edge-cases.json parses");
        v["cases"].as_array().expect("a `cases` array").clone()
    }

    fn series_kind(b: &Book) -> &'static str {
        match &b.series {
            None => "none",
            Some((_, Some(_))) => "indexed",
            Some((_, None)) => "unnumbered",
        }
    }

    fn state_name(s: State) -> &'static str {
        match s {
            State::Unread => "unread",
            State::Reading => "reading",
            State::Finished => "finished",
            State::Abandoned => "abandoned",
            State::Reread => "reread",
            State::Unknown => "other",
        }
    }

    /// Half of item 38. The other half is `gui/src/lib/api/fake.test.ts`,
    /// asserting the **same file** against the frontend's fixture.
    ///
    /// This is what makes adding a hostile case to one fixture and not the
    /// other a failure rather than a silence. It compares length first, so a
    /// case *removed* fails as loudly as one added — the direction a per-case
    /// loop misses.
    #[test]
    fn the_edge_cases_are_the_declared_ones() {
        let cases = declared();
        let ours = edge_cases();
        assert_eq!(
            ours.len(),
            cases.len(),
            "edge-cases.json declares {} cases and gen-devdb builds {}",
            cases.len(),
            ours.len()
        );

        for (i, (book, want)) in ours.iter().zip(cases.iter()).enumerate() {
            // `id` is positional: `generate` numbers the hostile set 1..=n ahead
            // of the ordinary books, so the declaration's id *is* the index, and
            // asserting it keeps the two orders locked together.
            let id = i as i64 + 1;
            assert_eq!(want["id"].as_i64(), Some(id), "case {i} is out of order");
            let at = format!("case {id} ({})", want["title"].as_str().unwrap_or(""));

            assert_eq!(
                Some(book.title.as_str()),
                want["title"].as_str(),
                "{at}: title"
            );
            let authors: Vec<&str> = want["authors"]
                .as_array()
                .expect("authors is an array")
                .iter()
                .map(|a| a.as_str().expect("an author is a string"))
                .collect();
            assert_eq!(book.authors, authors, "{at}: authors");
            assert_eq!(
                book.page_count,
                want["page_count"].as_i64(),
                "{at}: page_count"
            );
            assert_eq!(Some(book.cover), want["cover"].as_bool(), "{at}: cover");
            assert_eq!(
                Some(state_name(book.state)),
                want["state"].as_str(),
                "{at}: state"
            );
            assert_eq!(
                Some(series_kind(book)),
                want["series"].as_str(),
                "{at}: series"
            );
            assert_eq!(
                Some(book.subjects.len() as u64),
                want["subjects"].as_u64(),
                "{at}: subjects"
            );
        }
    }

    /// Exactly one declared case has no cover, and it is the one named for it.
    ///
    /// Asserted as a **partition** rather than by looking the title up, because
    /// the value of the no-cover case is that it is alone: every cover-bearing
    /// rule on the frontend's side is only assertable while exactly one row is
    /// missing a jacket.
    #[test]
    fn exactly_one_declared_case_has_no_cover() {
        let cases = declared();
        let without: Vec<&str> = cases
            .iter()
            .filter(|c| c["cover"].as_bool() == Some(false))
            .map(|c| c["title"].as_str().expect("a title"))
            .collect();
        assert_eq!(without, ["A Book With No Cover At All"]);
    }

    /// A stored title is never NULL, so the untitled case is the empty *string*.
    ///
    /// `books.title` is `TEXT NOT NULL DEFAULT ''` (`0001_init.sql`), which makes
    /// `Some("")` the reachable absence and `None` unreachable for anything that
    /// came out of the database. `fake.ts` modelled `null` here until item 38 —
    /// a state no library can produce.
    #[test]
    fn the_untitled_case_is_an_empty_string_and_not_an_absence() {
        let untitled = declared()
            .into_iter()
            .filter(|c| c["title"].as_str() == Some(""))
            .count();
        assert_eq!(untitled, 1, "one untitled case, and its title is a string");
    }
}
