//! Tier-1 fixtures: small, committed, and hostile.
//!
//! Every case here is a file KOReader or a user can genuinely produce. They are
//! generated rather than hand-written so the set stays reproducible and so the
//! minimal epub (a real zip with a real OPF) can be built at all.

use std::io::Write;
use std::path::Path;

/// Prefix on every generated directory, so a human can tell at a glance which
/// fixtures are hand-written and which come from `corpus gen-synthetic`.
const GEN: &str = "Gen-";

const HEADER: &str = "-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.\n";

pub fn generate(root: &Path) -> std::io::Result<usize> {
    let synthetic = root.join("synthetic");
    std::fs::create_dir_all(&synthetic)?;
    let mut n = 0;

    // 1. A chunk that never returns. `StdLib::NONE` removes the standard
    //    library but not the ability to loop, so without an instruction budget
    //    this hangs the import — and the whole app — forever.
    n += lua(
        &synthetic,
        "Runaway-Loop",
        "-- A non-terminating chunk. Must be killed by the instruction budget.\n\
         return (function() while true do end end)()\n",
    )?;

    // 2. A hole in the annotations table. `sequence_values` stops at the first
    //    missing index, so entries after the gap vanish silently. KOReader
    //    produces this shape after a sync conflict.
    n += lua(
        &synthetic,
        "Holey-Annotations",
        &format!(
            r#"{HEADER}-- Indices 1, 3, 4 — no 2. All three highlights must import.
return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "first entry",  ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 1, ["datetime"] = "2026-01-01 10:00:00" }},
        [3] = {{ ["text"] = "third entry",  ["pos0"] = "/body/p[3]/text().0",
                 ["pageno"] = 3, ["datetime"] = "2026-01-03 10:00:00" }},
        [4] = {{ ["text"] = "fourth entry", ["pos0"] = "/body/p[4]/text().0",
                 ["pageno"] = 4, ["datetime"] = "2026-01-04 10:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "Holey Book", ["authors"] = "A Syncer" }},
}}
"#
        ),
    )?;

    // 3. No `doc_props` at all: nothing to match on. Must land in `unmatched`
    //    rather than panicking or being silently dropped.
    n += lua(
        &synthetic,
        "No-Doc-Props",
        &format!(
            r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "orphaned highlight", ["pos0"] = "/body/p[1]/text().0",
                 ["datetime"] = "2026-01-01 10:00:00" }},
    }},
}}
"#
        ),
    )?;

    // 4. No datetimes anywhere. The identity hash then collapses onto
    //    (pos0, text), so two highlights at the same position must dedupe to
    //    one — and stay idempotent on re-import.
    n += lua(
        &synthetic,
        "No-Datetime",
        &format!(
            r#"{HEADER}-- Entries 1 and 2 are identical once datetime is absent from the hash.
return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "same position", ["pos0"] = "/body/p[1]/text().0", ["pageno"] = 1 }},
        [2] = {{ ["text"] = "same position", ["pos0"] = "/body/p[1]/text().0", ["pageno"] = 1 }},
        [3] = {{ ["text"] = "elsewhere",     ["pos0"] = "/body/p[9]/text().0", ["pageno"] = 9 }},
    }},
    ["doc_props"] = {{ ["title"] = "Undated Book", ["authors"] = "No Clock" }},
}}
"#
        ),
    )?;

    // 5. The same entry twice, verbatim. KOReader emits these after a sync
    //    conflict; the second must be `skipped` on the very first import, not
    //    only on a re-import.
    n += lua(
        &synthetic,
        "Duplicate-Entries",
        &format!(
            r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "said twice", ["pos0"] = "/body/p[2]/text().4",
                 ["pageno"] = 12, ["datetime"] = "2026-02-02 09:00:00" }},
        [2] = {{ ["text"] = "said twice", ["pos0"] = "/body/p[2]/text().4",
                 ["pageno"] = 12, ["datetime"] = "2026-02-02 09:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "Doubled Book", ["authors"] = "Sync Conflict" }},
}}
"#
        ),
    )?;

    // 6. Both layouts present. The parser's if/else-if means `annotations`
    //    wins; pin that precedence so it cannot drift unnoticed.
    n += lua(
        &synthetic,
        "Both-Layouts",
        &format!(
            r#"{HEADER}-- `annotations` must win; the legacy `highlight` table is ignored.
return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "from annotations", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 1, ["datetime"] = "2026-03-01 10:00:00" }},
    }},
    ["highlight"] = {{
        [99] = {{
            [1] = {{ ["text"] = "from legacy highlight", ["pos0"] = "/body/p[99]/text().0",
                     ["datetime"] = "2020-01-01 10:00:00" }},
        }},
    }},
    ["doc_props"] = {{ ["title"] = "Both Layouts", ["authors"] = "Two Eras" }},
}}
"#
        ),
    )?;

    // 7. Entries missing the fields that make a highlight a highlight. Empty
    //    text and absent pos0 are both bookmark-shaped and must be skipped,
    //    leaving only the one real highlight.
    n += lua(
        &synthetic,
        "Incomplete-Entries",
        &format!(
            r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "",           ["pos0"] = "/body/p[1]/text().0", ["pageno"] = 1,
                 ["datetime"] = "2026-04-01 10:00:00" }},
        [2] = {{ ["text"] = "no pos0 here", ["pageno"] = 2,
                 ["datetime"] = "2026-04-02 10:00:00" }},
        [3] = {{ ["text"] = "a real one",  ["pos0"] = "/body/p[3]/text().0", ["pageno"] = 3,
                 ["datetime"] = "2026-04-03 10:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "Incomplete Book", ["authors"] = "Half Written" }},
}}
"#
        ),
    )?;

    // 8. Not a table. Valid Lua, wrong shape.
    n += lua(&synthetic, "Not-A-Table", &format!("{HEADER}return 42\n"))?;

    // 9. A non-epub sidecar. `is_sidecar_file` accepts any `metadata.*.lua`,
    //    and a PDF-backed book is an ordinary thing to have in a library.
    //
    //    **This covers the file NAME and not the file's contents**, and the
    //    distinction was worth a fixture of its own (9b): the annotations below
    //    are cre xpointers, which is the shape a *reflowable* document gets. A
    //    real PDF anchors a highlight quite differently, and for years this
    //    fixture's name suggested that case was covered when it was not.
    {
        let dir = synthetic.join(format!("{GEN}Pdf-Sidecar.sdr"));
        std::fs::create_dir_all(&dir)?;
        std::fs::write(
            dir.join("metadata.pdf.lua"),
            format!(
                r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "from a pdf", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 7, ["datetime"] = "2026-05-01 10:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "A Scanned Book", ["authors"] = "Pdf Author" }},
}}
"#
            ),
        )?;
        n += 1;
    }

    // 9b. A PDF sidecar with PDF-shaped **anchors** (item 37).
    //
    //     On a paging document — PDF, DjVu — KOReader cannot anchor a highlight
    //     to a position in a text stream, because a scanned page has no text
    //     stream. So `pos0`/`pos1` are **tables**: a page plus coordinates, with
    //     a sibling `pboxes` array of the rectangles it drew. The engine's rule
    //     was `get_str(item, "pos0")?`, which on a table returns `None` — so
    //     every entry here used to be dropped in total silence, and a user with
    //     a PDF library imported nothing and was told nothing.
    //
    //     **What is asserted, and what is only illustrated.** *That `pos0` is a
    //     table rather than a string* is the fact this fixture exists to encode,
    //     and it is the only thing the engine reads: `koreader::anchor` branches
    //     on the value being a table and never on anything inside it. **The
    //     table's keys below are a reconstruction and not an observation** — no
    //     PDF sidecar with annotations has ever been read here (both real ones
    //     have an empty `annotations`, see docs/koreader-format.md §6) — so they
    //     are deliberately unread, and no golden can bless a key name. If a real
    //     device turns out to write `pos` or `rect` instead, nothing here or in
    //     the engine has to change.
    //
    //     Entry [4] is a plain bookmark with no `pos0` at all. It must stay
    //     *uncounted*: a bookmark is not a highlight that went missing, and a
    //     diagnostic that inflated its number would be a worse lie than silence.
    {
        let dir = synthetic.join(format!("{GEN}Pdf-Anchors.sdr"));
        std::fs::create_dir_all(&dir)?;
        std::fs::write(
            dir.join("metadata.pdf.lua"),
            format!(
                r#"{HEADER}-- pos0/pos1 are TABLES here, not xpointers. That, and only that, is what
-- this fixture asserts; the keys inside them are reconstructed and unread.
return {{
    ["annotations"] = {{
        [1] = {{
            ["chapter"] = "II. Of Scanned Things",
            ["color"] = "gray",
            ["datetime"] = "2026-05-02 11:15:00",
            ["drawer"] = "lighten",
            ["page"] = 3,
            ["pageno"] = 3,
            ["pboxes"] = {{
                [1] = {{ ["h"] = 16.5, ["w"] = 305.5, ["x"] = 96.5, ["y"] = 220.0 }},
            }},
            ["pos0"] = {{ ["page"] = 3, ["rotation"] = 0, ["x"] = 96.5, ["y"] = 220.0, ["zoom"] = 1.0 }},
            ["pos1"] = {{ ["page"] = 3, ["rotation"] = 0, ["x"] = 402.0, ["y"] = 236.5, ["zoom"] = 1.0 }},
            ["text"] = "a passage on a scanned page",
        }},
        [2] = {{
            ["chapter"] = "II. Of Scanned Things",
            ["color"] = "gray",
            ["datetime"] = "2026-05-02 11:22:41",
            ["datetime_updated"] = "2026-05-02 11:23:09",
            ["drawer"] = "underscore",
            ["page"] = 4,
            ["pageno"] = 4,
            ["note"] = "a note on a PDF highlight is lost with it, and must be counted",
            ["pos0"] = {{ ["page"] = 4, ["rotation"] = 0, ["x"] = 72.0, ["y"] = 118.25, ["zoom"] = 1.0 }},
            ["pos1"] = {{ ["page"] = 4, ["rotation"] = 0, ["x"] = 388.75, ["y"] = 134.0, ["zoom"] = 1.0 }},
            ["text"] = "a second passage, this one annotated",
        }},
        [3] = {{
            ["chapter"] = "III. Of Coordinates",
            ["color"] = "gray",
            ["datetime"] = "2026-05-03 09:04:12",
            ["drawer"] = "lighten",
            ["page"] = 9,
            ["pageno"] = 9,
            ["pos0"] = {{ ["page"] = 9, ["rotation"] = 0, ["x"] = 110.0, ["y"] = 512.5, ["zoom"] = 1.0 }},
            ["pos1"] = {{ ["page"] = 9, ["rotation"] = 0, ["x"] = 431.5, ["y"] = 528.0, ["zoom"] = 1.0 }},
            ["text"] = "a third passage",
        }},
        [4] = {{
            -- A plain bookmark: no pos0 of any shape. Not a highlight, never
            -- was, and must NOT be counted as one that failed to arrive.
            ["chapter"] = "III. Of Coordinates",
            ["datetime"] = "2026-05-03 09:40:00",
            ["page"] = 10,
            ["pageno"] = 10,
            ["text"] = "in III. Of Coordinates",
        }},
    }},
    ["doc_pages"] = 214,
    ["doc_props"] = {{ ["authors"] = "P. D. Fauthor", ["title"] = "A Scanned Monograph" }},
    ["partial_md5_checksum"] = "3c1f5a7e9b2d4068a1c3e5f70921436d",
    ["percent_finished"] = 0.31,
}}
"#
            ),
        )?;
        n += 1;
    }

    // 10. Invalid UTF-8. `read_to_string` fails here rather than the parser, so
    //     this is the case that used to abort an entire library import.
    {
        let dir = synthetic.join(format!("{GEN}Not-Utf8.sdr"));
        std::fs::create_dir_all(&dir)?;
        let mut bytes = b"-- GENERATED. Invalid UTF-8 follows.\nreturn { [\"text\"] = \"".to_vec();
        bytes.extend_from_slice(&[0xff, 0xfe, 0x80, 0x81]);
        bytes.extend_from_slice(b"\" }\n");
        std::fs::write(dir.join("metadata.epub.lua"), bytes)?;
        n += 1;
    }

    // 11. The sibling-epub ISBN path, in the layout KOReader actually produces:
    //     `<Title>.epub` beside `<Title>.sdr/`. Note the other fixtures use a
    //     bare `.sdr` with no sibling, which is NOT what a real device looks
    //     like — a standing fidelity gap this case closes.
    //
    //     The epub is built here rather than committed as an opaque blob so the
    //     ISBN inside it is visible and changeable.
    {
        let stem = format!("{GEN}Isbn-Match");
        let dir = synthetic.join(format!("{stem}.sdr"));
        std::fs::create_dir_all(&dir)?;
        std::fs::write(
            dir.join("metadata.epub.lua"),
            format!(
                r#"{HEADER}-- doc_props.title deliberately does NOT match the seeded library title,
-- so this fixture can only match via the sibling epub's ISBN. If the ISBN
-- path breaks, fuzzy title matching must not be able to rescue it.
return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "matched by isbn", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 5, ["datetime"] = "2026-06-01 10:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "Zzzz Unrelated Sidecar Title", ["authors"] = "Nobody" }},
}}
"#
            ),
        )?;
        write_minimal_epub(
            &synthetic.join(format!("{stem}.epub")),
            "The ISBN Matched Book",
            "9780316769488",
        )?;
        n += 2;
    }

    // 11b. An epub with a **real table of contents** (item 32), and no sidecar
    //      beside it: the TOC path is read off a file the library owns, not off
    //      anything KOReader wrote.
    //
    //      Built here rather than committed as a blob, like its neighbour, so
    //      the ncx that the parse is judged against is readable in the diff.
    //      It is a separate epub rather than an extension of `Gen-Isbn-Match`
    //      because that file's bytes are what the sibling-epub ISBN path and
    //      its goldens were built on, and a fixture that changes shape to serve
    //      a second test is a fixture two tests then disagree about.
    write_toc_epub(&synthetic.join(format!("{GEN}Toc-Chapters.epub")))?;
    n += 1;

    // 12. The device's own reading state: `summary` and `percent_finished`.
    //     Everything here is reported but deliberately NOT persisted — status,
    //     rating and progress belong to `readings` (build item 4), and parking
    //     them on `books` now would only have to be undone. The golden is what
    //     proves the parse happens at all in the meantime.
    //
    //     `summary.note` is the user's review. It is real in KOReader's source
    //     but written by no build we have seen, so this is the only place the
    //     field is exercised.
    n += lua(
        &synthetic,
        "Summary",
        &format!(
            r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "a passage in a finished book", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 11, ["datetime"] = "2026-07-01 10:00:00",
                 ["datetime_updated"] = "2026-07-01 10:00:27",
                 ["note"] = "edited 27s later; datetime must not have moved" }},
    }},
    ["doc_props"] = {{ ["title"] = "A Rated Book", ["authors"] = "Someone Rated" }},
    ["percent_finished"] = 0.99770326136886,
    ["summary"] = {{
        ["modified"] = "2026-07-22",
        ["note"] = "A few words about the book.",
        ["rating"] = 4,
        ["status"] = "complete",
    }},
}}
"#
        ),
    )?;

    // 13. The `stats` subtable, in the shape a 2024.11+ device actually writes
    //     it: NO `md5` and NO `total_time_in_sec`, both of which the spec
    //     assumed were there. `device_books` therefore keys on the root
    //     `partial_md5_checksum`, which this fixture carries — see
    //     docs/koreader-format.md §2.1.
    //
    //     `percent_finished` is the bare integer `1`, not `1.0`: that is how
    //     KOReader serialises a completed book, and a parser that demands a
    //     float silently loses it.
    n += lua(
        &synthetic,
        "Stats",
        &format!(
            r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "counted as a highlight", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 3, ["datetime"] = "2026-07-02 10:00:00" }},
        [2] = {{ ["text"] = "counted as a note", ["pos0"] = "/body/p[2]/text().0",
                 ["pageno"] = 4, ["datetime"] = "2026-07-02 11:00:00",
                 ["note"] = "stats.notes counts entries WITH a note" }},
    }},
    ["doc_pages"] = 412,
    ["doc_props"] = {{ ["title"] = "A Counted Book", ["authors"] = "Stat Keeper" }},
    ["partial_md5_checksum"] = "9f2c4e6a8b0d1357911d3f5b7d9f1a3c",
    ["percent_finished"] = 1,
    ["stats"] = {{
        ["authors"] = "Stat Keeper",
        ["highlights"] = 1,
        ["language"] = "en",
        ["notes"] = 1,
        ["pages"] = 412,
        ["performance_in_pages"] = {{}},
        ["series"] = "N/A",
        ["title"] = "A Counted Book",
    }},
}}
"#
        ),
    )?;

    // 14. Device state on a LEGACY sidecar. `summary`, `stats` and
    //     `percent_finished` are DocSettings *root* keys, written by subsystems
    //     that never look at the annotations layout — so a pre-2024 file
    //     carries them too. Source-derived: no legacy sidecar exists in the
    //     real corpus to check against, which is exactly why it is pinned here.
    //
    //     A legacy file is also the most likely place `stats.md5` and
    //     `total_time_in_sec` still appear, since the pre-DB statistics plugin
    //     predates the annotations format. This is the only coverage they get.
    n += lua(
        &synthetic,
        "Summary-Legacy",
        &format!(
            r#"{HEADER}-- No `annotations` key: the parser must take the legacy branch AND still
-- read the root-level device state.
return {{
    ["bookmarks"] = {{
        [1] = {{
            ["datetime"] = "2021-05-02 22:30:00",
            ["notes"] = "an older passage",
            ["text"] = "the note lives in bookmarks, joined by datetime",
        }},
    }},
    ["highlight"] = {{
        [7] = {{
            [1] = {{ ["datetime"] = "2021-05-02 22:30:00", ["chapter"] = "I",
                     ["text"] = "an older passage", ["pos0"] = "/body/p[7]/text().0",
                     ["pos1"] = "/body/p[7]/text().16", ["drawer"] = "lighten" }},
        }},
    }},
    ["doc_props"] = {{ ["title"] = "An Old Book", ["authors"] = "Legacy Format" }},
    ["percent_finished"] = 0.5,
    ["stats"] = {{
        ["authors"] = "Legacy Format",
        ["md5"] = "1b3d5f7911d3f5b7d9f1a3c5e7092b4d",
        ["pages"] = 180,
        ["title"] = "An Old Book",
        ["total_time_in_sec"] = 7200,
    }},
    ["summary"] = {{
        ["modified"] = "2021-05-03",
        ["rating"] = 3,
        ["status"] = "abandoned",
    }},
}}
"#
        ),
    )?;

    // 15. A status KOReader does not write today. It must import cleanly and
    //     round-trip as `KoStatus::Other`, never fail the import — a future
    //     KOReader adding a status must not cost somebody their highlights.
    //
    //     It also warns, and that warning is the point: it is the only signal
    //     we would ever get that the device grew a status we do not model, and
    //     silence would be indistinguishable from success. The golden's
    //     `has_warnings` is what asserts it.
    n += lua(
        &synthetic,
        "Summary-Unknown-Status",
        &format!(
            r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "still imported", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 1, ["datetime"] = "2026-07-03 10:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "A Future Book", ["authors"] = "Not Yet Written" }},
    ["percent_finished"] = 0.0,
    ["summary"] = {{
        ["modified"] = "2026-07-23",
        ["status"] = "tbr",
    }},
}}
"#
        ),
    )?;

    // 16. A note edited on the device: `Pachinko.sdr` with one existing
    //     annotation's `note` rewritten and a `datetime_updated` stamped on it.
    //     Everything that takes part in the identity hash — `datetime`, `pos0`,
    //     `text` — is untouched, so the highlight must be recognised as the
    //     same row and refreshed, not re-inserted.
    //
    //     Sibling to `variants/Pachinko-Superset.sdr` and there for the same
    //     recorded reason: a committed fixture, not a string splice. The test
    //     that needed one of these used to `replacen` against Pachinko's
    //     literal indentation, so reformatting that file broke it silently.
    //
    //     Under `variants/` because fixture discovery is a NON-recursive
    //     read_dir: invisible to the golden loop, so it needs no golden of its
    //     own and does not perturb the ones that exist.
    n += variant(
        &synthetic,
        "Pachinko-NoteEdited",
        &format!(
            r#"{HEADER}-- ../../Pachinko.sdr with entry [1]'s note rewritten on the device.
-- `datetime`, `pos0` and `text` are byte-identical, so the identity hash is
-- unchanged: this is the SAME highlight with a new note, not a new one.
return {{
    ["annotations"] = {{
        [1] = {{
            ["chapter"] = "Chapter One",
            ["datetime"] = "2026-01-05 21:14:08",
            ["datetime_updated"] = "2026-02-14 07:31:52",
            ["drawer"] = "lighten",
            ["color"] = "yellow",
            ["page"] = "/body/DocFragment[8]/body/p[12]/text().0",
            ["pageno"] = 42,
            ["pos0"] = "/body/DocFragment[8]/body/p[12]/text().0",
            ["pos1"] = "/body/DocFragment[8]/body/p[12]/text().57",
            ["text"] = "History has failed us, but no matter.",
            ["note"] = "Rewritten on the device weeks later.",
        }},
        [2] = {{
            ["chapter"] = "Chapter Two",
            ["datetime"] = "2026-01-06 08:02:11",
            ["drawer"] = "lighten",
            ["pageno"] = 55,
            ["pos0"] = "/body/DocFragment[9]/body/p[4]/text().10",
            ["pos1"] = "/body/DocFragment[9]/body/p[4]/text().19",
            ["text"] = "pachinko",
        }},
        [3] = {{
            -- plain bookmark, no pos0: must be skipped
            ["datetime"] = "2026-01-06 09:00:00",
            ["pageno"] = 60,
            ["text"] = "dogear",
        }},
    }},
    ["doc_props"] = {{
        ["authors"] = "Min Jin Lee",
        ["title"] = "Pachinko",
        ["language"] = "en",
    }},
    ["partial_md5_checksum"] = "0d6ba6c47caf63b8b3d1a2b3c4d5e6f7",
}}
"#
        ),
    )?;

    Ok(n)
}

/// Write `variants/<name>.sdr/metadata.epub.lua`.
///
/// No `Gen-` prefix, unlike [`lua`]: `variants/` is not the auto-discovered
/// fixture dir, its two entries are named after the fixture they vary, and the
/// `GENERATED` header inside the file carries the same warning the prefix does.
fn variant(synthetic: &Path, name: &str, body: &str) -> std::io::Result<usize> {
    let dir = synthetic.join("variants").join(format!("{name}.sdr"));
    std::fs::create_dir_all(&dir)?;
    std::fs::write(dir.join("metadata.epub.lua"), body)?;
    Ok(1)
}

/// Write `<name>.sdr/metadata.epub.lua`.
fn lua(synthetic: &Path, name: &str, body: &str) -> std::io::Result<usize> {
    let dir = synthetic.join(format!("{GEN}{name}.sdr"));
    std::fs::create_dir_all(&dir)?;
    let contents = if body.starts_with("-- GENERATED") {
        body.to_string()
    } else {
        format!("{HEADER}{body}")
    };
    std::fs::write(dir.join("metadata.epub.lua"), contents)?;
    Ok(1)
}

/// An epub whose `toc.ncx` is the point: three top-level chapters, one of them
/// with two nested sections, and one entry pointing at a **fragment** inside a
/// document the spine already carries.
///
/// Three details are deliberate, and each of them is a way the parse can be
/// wrong while still returning something:
///
/// * **`playOrder` is on every `navPoint`.** The reader silently drops any that
///   lacks one, and it sorts by that number rather than by document order — so
///   `ch3` is declared *before* `ch2` here, and the flattened list must still
///   come back in reading order.
/// * **A nested `navPoint` is inside its parent**, not a sibling with a deeper
///   `class`, so depth is structural.
/// * **The fragment entry** (`ch2.xhtml#part-two`) must keep its fragment in the
///   target and still resolve to `ch2`'s spine position: the spine is keyed on
///   resources and no resource is ever named with a `#`.
///
/// The manifest carries the ncx and the spine names it with `toc="ncx"`, which
/// is the attribute the reader keys the whole thing on — without it there is no
/// table of contents however well-formed the file is.
fn write_toc_epub(path: &Path) -> std::io::Result<()> {
    use zip::write::SimpleFileOptions;

    let file = std::fs::File::create(path)?;
    let mut zip = zip::ZipWriter::new(file);

    zip.start_file(
        "mimetype",
        SimpleFileOptions::default().compression_method(zip::CompressionMethod::Stored),
    )?;
    zip.write_all(b"application/epub+zip")?;

    let opts = SimpleFileOptions::default();

    zip.start_file("META-INF/container.xml", opts)?;
    zip.write_all(
        br#"<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
"#,
    )?;

    zip.start_file("OEBPS/content.opf", opts)?;
    zip.write_all(
        br#"<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="bookid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="bookid">urn:isbn:9780306406157</dc:identifier>
    <dc:title>A Book With Chapters</dc:title>
    <dc:creator>A Generated Author</dc:creator>
    <dc:language>en</dc:language>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="ch1" href="ch1.xhtml" media-type="application/xhtml+xml"/>
    <item id="ch2" href="ch2.xhtml" media-type="application/xhtml+xml"/>
    <item id="ch3" href="ch3.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine toc="ncx">
    <itemref idref="ch1"/>
    <itemref idref="ch2"/>
    <itemref idref="ch3"/>
  </spine>
</package>
"#,
    )?;

    // `ch3` is declared before `ch2` on purpose: reading order is `playOrder`,
    // never the order the navPoints happen to appear in.
    zip.start_file("OEBPS/toc.ncx", opts)?;
    zip.write_all(
        br#"<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <docTitle><text>A Book With Chapters</text></docTitle>
  <navMap>
    <navPoint id="np1" playOrder="1">
      <navLabel><text>One: The Beginning</text></navLabel>
      <content src="ch1.xhtml"/>
    </navPoint>
    <navPoint id="np4" playOrder="4">
      <navLabel><text>Three: The End</text></navLabel>
      <content src="ch3.xhtml"/>
    </navPoint>
    <navPoint id="np2" playOrder="2">
      <navLabel><text>Two: The Middle</text></navLabel>
      <content src="ch2.xhtml"/>
      <navPoint id="np3" playOrder="3">
        <navLabel><text>Two, part two</text></navLabel>
        <content src="ch2.xhtml#part-two"/>
      </navPoint>
    </navPoint>
  </navMap>
</ncx>
"#,
    )?;

    for (id, title) in [
        ("ch1", "One: The Beginning"),
        ("ch2", "Two: The Middle"),
        ("ch3", "Three: The End"),
    ] {
        zip.start_file(format!("OEBPS/{id}.xhtml"), opts)?;
        zip.write_all(
            format!(
                r#"<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>{title}</title></head>
<body><h1>{title}</h1><p id="part-two">A paragraph, so the document is not empty.</p></body></html>
"#
            )
            .as_bytes(),
        )?;
    }

    zip.finish()?;
    Ok(())
}

/// A genuinely valid, ~2 KB epub carrying an ISBN in its OPF.
///
/// Built rather than committed as a blob so what is inside it — in particular
/// the identifier the ISBN match path reads — stays readable in the diff.
fn write_minimal_epub(path: &Path, title: &str, isbn: &str) -> std::io::Result<()> {
    use zip::write::SimpleFileOptions;

    let file = std::fs::File::create(path)?;
    let mut zip = zip::ZipWriter::new(file);

    // `mimetype` must be first and STORED (uncompressed) per the epub spec.
    zip.start_file(
        "mimetype",
        SimpleFileOptions::default().compression_method(zip::CompressionMethod::Stored),
    )?;
    zip.write_all(b"application/epub+zip")?;

    let opts = SimpleFileOptions::default();

    zip.start_file("META-INF/container.xml", opts)?;
    zip.write_all(
        br#"<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
"#,
    )?;

    zip.start_file("OEBPS/content.opf", opts)?;
    zip.write_all(
        format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="bookid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="uuid">urn:uuid:00000000-0000-4000-8000-000000000000</dc:identifier>
    <dc:identifier id="bookid">urn:isbn:{isbn}</dc:identifier>
    <dc:title>{title}</dc:title>
    <dc:creator>A Generated Author</dc:creator>
    <dc:language>en</dc:language>
  </metadata>
  <manifest>
    <item id="ch1" href="ch1.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine>
    <itemref idref="ch1"/>
  </spine>
</package>
"#
        )
        .as_bytes(),
    )?;

    zip.start_file("OEBPS/ch1.xhtml", opts)?;
    zip.write_all(
        format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>{title}</title></head>
<body><h1>{title}</h1><p>A single paragraph, so the spine is not empty.</p></body></html>
"#
        )
        .as_bytes(),
    )?;

    zip.finish()?;
    Ok(())
}
