//! Tier-1 fixtures: small, committed, and hostile.
//!
//! Every case here is a file KOReader or a user can genuinely produce. They are
//! generated rather than hand-written so the set stays reproducible and so the
//! minimal epub (a real zip with a real OPF) can be built at all.

use std::io::Write;
use std::path::Path;

/// Prefix on every generated directory, so a human can tell at a glance which
/// fixtures are hand-written and which come from `corpus gen-synthetic`.
const GEN: &str = "Gen-";

const HEADER: &str = "-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.\n";

pub fn generate(root: &Path) -> std::io::Result<usize> {
    let synthetic = root.join("synthetic");
    std::fs::create_dir_all(&synthetic)?;
    let mut n = 0;

    // 1. A chunk that never returns. `StdLib::NONE` removes the standard
    //    library but not the ability to loop, so without an instruction budget
    //    this hangs the import — and the whole app — forever.
    n += lua(
        &synthetic,
        "Runaway-Loop",
        "-- A non-terminating chunk. Must be killed by the instruction budget.\n\
         return (function() while true do end end)()\n",
    )?;

    // 2. A hole in the annotations table. `sequence_values` stops at the first
    //    missing index, so entries after the gap vanish silently. KOReader
    //    produces this shape after a sync conflict.
    n += lua(
        &synthetic,
        "Holey-Annotations",
        &format!(
            r#"{HEADER}-- Indices 1, 3, 4 — no 2. All three highlights must import.
return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "first entry",  ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 1, ["datetime"] = "2026-01-01 10:00:00" }},
        [3] = {{ ["text"] = "third entry",  ["pos0"] = "/body/p[3]/text().0",
                 ["pageno"] = 3, ["datetime"] = "2026-01-03 10:00:00" }},
        [4] = {{ ["text"] = "fourth entry", ["pos0"] = "/body/p[4]/text().0",
                 ["pageno"] = 4, ["datetime"] = "2026-01-04 10:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "Holey Book", ["authors"] = "A Syncer" }},
}}
"#
        ),
    )?;

    // 3. No `doc_props` at all: nothing to match on. Must land in `unmatched`
    //    rather than panicking or being silently dropped.
    n += lua(
        &synthetic,
        "No-Doc-Props",
        &format!(
            r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "orphaned highlight", ["pos0"] = "/body/p[1]/text().0",
                 ["datetime"] = "2026-01-01 10:00:00" }},
    }},
}}
"#
        ),
    )?;

    // 4. No datetimes anywhere. The identity hash then collapses onto
    //    (pos0, text), so two highlights at the same position must dedupe to
    //    one — and stay idempotent on re-import.
    n += lua(
        &synthetic,
        "No-Datetime",
        &format!(
            r#"{HEADER}-- Entries 1 and 2 are identical once datetime is absent from the hash.
return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "same position", ["pos0"] = "/body/p[1]/text().0", ["pageno"] = 1 }},
        [2] = {{ ["text"] = "same position", ["pos0"] = "/body/p[1]/text().0", ["pageno"] = 1 }},
        [3] = {{ ["text"] = "elsewhere",     ["pos0"] = "/body/p[9]/text().0", ["pageno"] = 9 }},
    }},
    ["doc_props"] = {{ ["title"] = "Undated Book", ["authors"] = "No Clock" }},
}}
"#
        ),
    )?;

    // 5. The same entry twice, verbatim. KOReader emits these after a sync
    //    conflict; the second must be `skipped` on the very first import, not
    //    only on a re-import.
    n += lua(
        &synthetic,
        "Duplicate-Entries",
        &format!(
            r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "said twice", ["pos0"] = "/body/p[2]/text().4",
                 ["pageno"] = 12, ["datetime"] = "2026-02-02 09:00:00" }},
        [2] = {{ ["text"] = "said twice", ["pos0"] = "/body/p[2]/text().4",
                 ["pageno"] = 12, ["datetime"] = "2026-02-02 09:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "Doubled Book", ["authors"] = "Sync Conflict" }},
}}
"#
        ),
    )?;

    // 6. Both layouts present. The parser's if/else-if means `annotations`
    //    wins; pin that precedence so it cannot drift unnoticed.
    n += lua(
        &synthetic,
        "Both-Layouts",
        &format!(
            r#"{HEADER}-- `annotations` must win; the legacy `highlight` table is ignored.
return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "from annotations", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 1, ["datetime"] = "2026-03-01 10:00:00" }},
    }},
    ["highlight"] = {{
        [99] = {{
            [1] = {{ ["text"] = "from legacy highlight", ["pos0"] = "/body/p[99]/text().0",
                     ["datetime"] = "2020-01-01 10:00:00" }},
        }},
    }},
    ["doc_props"] = {{ ["title"] = "Both Layouts", ["authors"] = "Two Eras" }},
}}
"#
        ),
    )?;

    // 7. Entries missing the fields that make a highlight a highlight. Empty
    //    text and absent pos0 are both bookmark-shaped and must be skipped,
    //    leaving only the one real highlight.
    n += lua(
        &synthetic,
        "Incomplete-Entries",
        &format!(
            r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "",           ["pos0"] = "/body/p[1]/text().0", ["pageno"] = 1,
                 ["datetime"] = "2026-04-01 10:00:00" }},
        [2] = {{ ["text"] = "no pos0 here", ["pageno"] = 2,
                 ["datetime"] = "2026-04-02 10:00:00" }},
        [3] = {{ ["text"] = "a real one",  ["pos0"] = "/body/p[3]/text().0", ["pageno"] = 3,
                 ["datetime"] = "2026-04-03 10:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "Incomplete Book", ["authors"] = "Half Written" }},
}}
"#
        ),
    )?;

    // 8. Not a table. Valid Lua, wrong shape.
    n += lua(&synthetic, "Not-A-Table", &format!("{HEADER}return 42\n"))?;

    // 9. A non-epub sidecar. `is_sidecar_file` accepts any `metadata.*.lua`,
    //    and a PDF-backed book is an ordinary thing to have in a library.
    {
        let dir = synthetic.join(format!("{GEN}Pdf-Sidecar.sdr"));
        std::fs::create_dir_all(&dir)?;
        std::fs::write(
            dir.join("metadata.pdf.lua"),
            format!(
                r#"{HEADER}return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "from a pdf", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 7, ["datetime"] = "2026-05-01 10:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "A Scanned Book", ["authors"] = "Pdf Author" }},
}}
"#
            ),
        )?;
        n += 1;
    }

    // 10. Invalid UTF-8. `read_to_string` fails here rather than the parser, so
    //     this is the case that used to abort an entire library import.
    {
        let dir = synthetic.join(format!("{GEN}Not-Utf8.sdr"));
        std::fs::create_dir_all(&dir)?;
        let mut bytes = b"-- GENERATED. Invalid UTF-8 follows.\nreturn { [\"text\"] = \"".to_vec();
        bytes.extend_from_slice(&[0xff, 0xfe, 0x80, 0x81]);
        bytes.extend_from_slice(b"\" }\n");
        std::fs::write(dir.join("metadata.epub.lua"), bytes)?;
        n += 1;
    }

    // 11. The sibling-epub ISBN path, in the layout KOReader actually produces:
    //     `<Title>.epub` beside `<Title>.sdr/`. Note the other fixtures use a
    //     bare `.sdr` with no sibling, which is NOT what a real device looks
    //     like — a standing fidelity gap this case closes.
    //
    //     The epub is built here rather than committed as an opaque blob so the
    //     ISBN inside it is visible and changeable.
    {
        let stem = format!("{GEN}Isbn-Match");
        let dir = synthetic.join(format!("{stem}.sdr"));
        std::fs::create_dir_all(&dir)?;
        std::fs::write(
            dir.join("metadata.epub.lua"),
            format!(
                r#"{HEADER}-- doc_props.title deliberately does NOT match the seeded library title,
-- so this fixture can only match via the sibling epub's ISBN. If the ISBN
-- path breaks, fuzzy title matching must not be able to rescue it.
return {{
    ["annotations"] = {{
        [1] = {{ ["text"] = "matched by isbn", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 5, ["datetime"] = "2026-06-01 10:00:00" }},
    }},
    ["doc_props"] = {{ ["title"] = "Zzzz Unrelated Sidecar Title", ["authors"] = "Nobody" }},
}}
"#
            ),
        )?;
        write_minimal_epub(
            &synthetic.join(format!("{stem}.epub")),
            "The ISBN Matched Book",
            "9780316769488",
        )?;
        n += 2;
    }

    Ok(n)
}

/// Write `<name>.sdr/metadata.epub.lua`.
fn lua(synthetic: &Path, name: &str, body: &str) -> std::io::Result<usize> {
    let dir = synthetic.join(format!("{GEN}{name}.sdr"));
    std::fs::create_dir_all(&dir)?;
    let contents = if body.starts_with("-- GENERATED") {
        body.to_string()
    } else {
        format!("{HEADER}{body}")
    };
    std::fs::write(dir.join("metadata.epub.lua"), contents)?;
    Ok(1)
}

/// A genuinely valid, ~2 KB epub carrying an ISBN in its OPF.
///
/// Built rather than committed as a blob so what is inside it — in particular
/// the identifier the ISBN match path reads — stays readable in the diff.
fn write_minimal_epub(path: &Path, title: &str, isbn: &str) -> std::io::Result<()> {
    use zip::write::SimpleFileOptions;

    let file = std::fs::File::create(path)?;
    let mut zip = zip::ZipWriter::new(file);

    // `mimetype` must be first and STORED (uncompressed) per the epub spec.
    zip.start_file(
        "mimetype",
        SimpleFileOptions::default().compression_method(zip::CompressionMethod::Stored),
    )?;
    zip.write_all(b"application/epub+zip")?;

    let opts = SimpleFileOptions::default();

    zip.start_file("META-INF/container.xml", opts)?;
    zip.write_all(
        br#"<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
"#,
    )?;

    zip.start_file("OEBPS/content.opf", opts)?;
    zip.write_all(
        format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="bookid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="uuid">urn:uuid:00000000-0000-4000-8000-000000000000</dc:identifier>
    <dc:identifier id="bookid">urn:isbn:{isbn}</dc:identifier>
    <dc:title>{title}</dc:title>
    <dc:creator>A Generated Author</dc:creator>
    <dc:language>en</dc:language>
  </metadata>
  <manifest>
    <item id="ch1" href="ch1.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine>
    <itemref idref="ch1"/>
  </spine>
</package>
"#
        )
        .as_bytes(),
    )?;

    zip.start_file("OEBPS/ch1.xhtml", opts)?;
    zip.write_all(
        format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>{title}</title></head>
<body><h1>{title}</h1><p>A single paragraph, so the spine is not empty.</p></body></html>
"#
        )
        .as_bytes(),
    )?;

    zip.finish()?;
    Ok(())
}
