-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.
return {
    ["annotations"] = {
        [1] = { ["text"] = "a passage in a finished book", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 11, ["datetime"] = "2026-07-01 10:00:00",
                 ["datetime_updated"] = "2026-07-01 10:00:27",
                 ["note"] = "edited 27s later; datetime must not have moved" },
    },
    ["doc_props"] = { ["title"] = "A Rated Book", ["authors"] = "Someone Rated" },
    ["percent_finished"] = 0.99770326136886,
    ["summary"] = {
        ["modified"] = "2026-07-22",
        ["note"] = "A few words about the book.",
        ["rating"] = 4,
        ["status"] = "complete",
    },
}
