-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.
-- doc_props.title deliberately does NOT match the seeded library title,
-- so this fixture can only match via the sibling epub's ISBN. If the ISBN
-- path breaks, fuzzy title matching must not be able to rescue it.
return {
    ["annotations"] = {
        [1] = { ["text"] = "matched by isbn", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 5, ["datetime"] = "2026-06-01 10:00:00" },
    },
    ["doc_props"] = { ["title"] = "Zzzz Unrelated Sidecar Title", ["authors"] = "Nobody" },
}
