-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.
-- No `annotations` key: the parser must take the legacy branch AND still
-- read the root-level device state.
return {
    ["bookmarks"] = {
        [1] = {
            ["datetime"] = "2021-05-02 22:30:00",
            ["notes"] = "an older passage",
            ["text"] = "the note lives in bookmarks, joined by datetime",
        },
    },
    ["highlight"] = {
        [7] = {
            [1] = { ["datetime"] = "2021-05-02 22:30:00", ["chapter"] = "I",
                     ["text"] = "an older passage", ["pos0"] = "/body/p[7]/text().0",
                     ["pos1"] = "/body/p[7]/text().16", ["drawer"] = "lighten" },
        },
    },
    ["doc_props"] = { ["title"] = "An Old Book", ["authors"] = "Legacy Format" },
    ["percent_finished"] = 0.5,
    ["stats"] = {
        ["authors"] = "Legacy Format",
        ["md5"] = "1b3d5f7911d3f5b7d9f1a3c5e7092b4d",
        ["pages"] = 180,
        ["title"] = "An Old Book",
        ["total_time_in_sec"] = 7200,
    },
    ["summary"] = {
        ["modified"] = "2021-05-03",
        ["rating"] = 3,
        ["status"] = "abandoned",
    },
}
