-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.
-- Entries 1 and 2 are identical once datetime is absent from the hash.
return {
    ["annotations"] = {
        [1] = { ["text"] = "same position", ["pos0"] = "/body/p[1]/text().0", ["pageno"] = 1 },
        [2] = { ["text"] = "same position", ["pos0"] = "/body/p[1]/text().0", ["pageno"] = 1 },
        [3] = { ["text"] = "elsewhere",     ["pos0"] = "/body/p[9]/text().0", ["pageno"] = 9 },
    },
    ["doc_props"] = { ["title"] = "Undated Book", ["authors"] = "No Clock" },
}
