-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.
return {
    ["annotations"] = {
        [1] = { ["text"] = "",           ["pos0"] = "/body/p[1]/text().0", ["pageno"] = 1,
                 ["datetime"] = "2026-04-01 10:00:00" },
        [2] = { ["text"] = "no pos0 here", ["pageno"] = 2,
                 ["datetime"] = "2026-04-02 10:00:00" },
        [3] = { ["text"] = "a real one",  ["pos0"] = "/body/p[3]/text().0", ["pageno"] = 3,
                 ["datetime"] = "2026-04-03 10:00:00" },
    },
    ["doc_props"] = { ["title"] = "Incomplete Book", ["authors"] = "Half Written" },
}
