-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.
return {
    ["annotations"] = {
        [1] = { ["text"] = "still imported", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 1, ["datetime"] = "2026-07-03 10:00:00" },
    },
    ["doc_props"] = { ["title"] = "A Future Book", ["authors"] = "Not Yet Written" },
    ["percent_finished"] = 0.0,
    ["summary"] = {
        ["modified"] = "2026-07-23",
        ["status"] = "tbr",
    },
}
