-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.
return {
    ["annotations"] = {
        [1] = { ["text"] = "counted as a highlight", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 3, ["datetime"] = "2026-07-02 10:00:00" },
        [2] = { ["text"] = "counted as a note", ["pos0"] = "/body/p[2]/text().0",
                 ["pageno"] = 4, ["datetime"] = "2026-07-02 11:00:00",
                 ["note"] = "stats.notes counts entries WITH a note" },
    },
    ["doc_pages"] = 412,
    ["doc_props"] = { ["title"] = "A Counted Book", ["authors"] = "Stat Keeper" },
    ["partial_md5_checksum"] = "9f2c4e6a8b0d1357911d3f5b7d9f1a3c",
    ["percent_finished"] = 1,
    ["stats"] = {
        ["authors"] = "Stat Keeper",
        ["highlights"] = 1,
        ["language"] = "en",
        ["notes"] = 1,
        ["pages"] = 412,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "A Counted Book",
    },
}
