-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.
-- pos0/pos1 are TABLES here, not xpointers. That, and only that, is what
-- this fixture asserts; the keys inside them are reconstructed and unread.
return {
    ["annotations"] = {
        [1] = {
            ["chapter"] = "II. Of Scanned Things",
            ["color"] = "gray",
            ["datetime"] = "2026-05-02 11:15:00",
            ["drawer"] = "lighten",
            ["page"] = 3,
            ["pageno"] = 3,
            ["pboxes"] = {
                [1] = { ["h"] = 16.5, ["w"] = 305.5, ["x"] = 96.5, ["y"] = 220.0 },
            },
            ["pos0"] = { ["page"] = 3, ["rotation"] = 0, ["x"] = 96.5, ["y"] = 220.0, ["zoom"] = 1.0 },
            ["pos1"] = { ["page"] = 3, ["rotation"] = 0, ["x"] = 402.0, ["y"] = 236.5, ["zoom"] = 1.0 },
            ["text"] = "a passage on a scanned page",
        },
        [2] = {
            ["chapter"] = "II. Of Scanned Things",
            ["color"] = "gray",
            ["datetime"] = "2026-05-02 11:22:41",
            ["datetime_updated"] = "2026-05-02 11:23:09",
            ["drawer"] = "underscore",
            ["page"] = 4,
            ["pageno"] = 4,
            ["note"] = "a note on a PDF highlight is lost with it, and must be counted",
            ["pos0"] = { ["page"] = 4, ["rotation"] = 0, ["x"] = 72.0, ["y"] = 118.25, ["zoom"] = 1.0 },
            ["pos1"] = { ["page"] = 4, ["rotation"] = 0, ["x"] = 388.75, ["y"] = 134.0, ["zoom"] = 1.0 },
            ["text"] = "a second passage, this one annotated",
        },
        [3] = {
            ["chapter"] = "III. Of Coordinates",
            ["color"] = "gray",
            ["datetime"] = "2026-05-03 09:04:12",
            ["drawer"] = "lighten",
            ["page"] = 9,
            ["pageno"] = 9,
            ["pos0"] = { ["page"] = 9, ["rotation"] = 0, ["x"] = 110.0, ["y"] = 512.5, ["zoom"] = 1.0 },
            ["pos1"] = { ["page"] = 9, ["rotation"] = 0, ["x"] = 431.5, ["y"] = 528.0, ["zoom"] = 1.0 },
            ["text"] = "a third passage",
        },
        [4] = {
            -- A plain bookmark: no pos0 of any shape. Not a highlight, never
            -- was, and must NOT be counted as one that failed to arrive.
            ["chapter"] = "III. Of Coordinates",
            ["datetime"] = "2026-05-03 09:40:00",
            ["page"] = 10,
            ["pageno"] = 10,
            ["text"] = "in III. Of Coordinates",
        },
    },
    ["doc_pages"] = 214,
    ["doc_props"] = { ["authors"] = "P. D. Fauthor", ["title"] = "A Scanned Monograph" },
    ["partial_md5_checksum"] = "3c1f5a7e9b2d4068a1c3e5f70921436d",
    ["percent_finished"] = 0.31,
}
