use std::path::{Path, PathBuf};

use epub::doc::EpubDoc;

use crate::book::normalize_isbn;
use crate::error::{EngineError, Result};
use crate::notes::slugify;

#[derive(Debug, Default)]
pub struct EpubInfo {
    pub isbn: Option<String>,
    pub title: Option<String>,
    pub authors: Vec<String>,
    pub language: Option<String>,
}

/// Read epub metadata. Scans ALL identifier entries for the first one that
/// validates as an ISBN (identifiers are often UUIDs or urn:isbn: forms).
pub fn epub_info(path: &Path) -> Result<EpubInfo> {
    let doc =
        EpubDoc::new(path).map_err(|e| EngineError::Epub(format!("{}: {e}", path.display())))?;
    let mut info = EpubInfo::default();
    for (key, values) in doc.metadata.iter() {
        match key.as_str() {
            "identifier" => {
                if info.isbn.is_none() {
                    info.isbn = values.iter().find_map(|v| normalize_isbn(v));
                }
            }
            "title" => info.title = values.first().cloned(),
            "creator" => info.authors = values.clone(),
            "language" => info.language = values.first().cloned(),
            _ => {}
        }
    }
    Ok(info)
}

/// Extract the embedded cover image into `images_dir`; returns the written
/// path. Extension guessed from the cover's mime type.
pub fn extract_cover(path: &Path, images_dir: &Path) -> Result<Option<PathBuf>> {
    let mut doc =
        EpubDoc::new(path).map_err(|e| EngineError::Epub(format!("{}: {e}", path.display())))?;
    let Some((data, mime)) = doc.get_cover() else {
        return Ok(None);
    };
    let ext = match mime.as_str() {
        "image/png" => "png",
        "image/gif" => "gif",
        "image/webp" => "webp",
        _ => "jpg",
    };
    let title = doc.mdata("title").unwrap_or_else(|| "cover".to_string());
    std::fs::create_dir_all(images_dir)?;
    let file = images_dir.join(format!("{}.{ext}", slugify(&title)));
    std::fs::write(&file, &data)?;
    Ok(Some(file))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A real, committed epub — generated by `cargo run -p corpus --
    /// gen-synthetic`, ~2 KB, with a known ISBN in its OPF. Unconditional, so
    /// these tests actually run on every machine and in CI.
    fn generated_fixture() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/koreader/synthetic/Gen-Isbn-Match.epub")
    }

    /// The user's own sample epubs, which live in a gitignored dir.
    fn optional_fixture() -> Option<PathBuf> {
        let p = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../epubs/pachinko.epub");
        p.exists().then_some(p)
    }

    /// A skip must be loud, and refusable. Both tests below used to `return`
    /// silently when their fixture was absent — which is every machine without
    /// `epubs/` — so they were green without asserting anything.
    /// `READINGBUDDY_REQUIRE_FIXTURES=1` turns every such skip into a failure,
    /// which is what the nightly job sets so a broken fetch cannot masquerade
    /// as a passing build.
    fn skip(reason: &str) {
        if std::env::var("READINGBUDDY_REQUIRE_FIXTURES").is_ok() {
            panic!("REQUIRE_FIXTURES set but {reason}");
        }
        eprintln!("SKIPPED: {reason}");
    }

    #[test]
    fn reads_metadata_from_the_generated_epub() {
        let info = epub_info(&generated_fixture()).expect("generated fixture must parse");
        assert_eq!(info.title.as_deref(), Some("The ISBN Matched Book"));
        assert_eq!(info.language.as_deref(), Some("en"));
        // The OPF carries a uuid identifier *before* the isbn one; picking the
        // ISBN out means scanning them all rather than taking the first.
        assert_eq!(info.isbn.as_deref(), Some("9780316769488"));
    }

    #[test]
    fn a_nonexistent_epub_is_an_error_not_a_panic() {
        let err = epub_info(Path::new("/definitely/not/here.epub")).unwrap_err();
        assert!(matches!(err, EngineError::Epub(_)), "{err:?}");
    }

    /// Users import arbitrary files. A corrupt one must be rejected, never
    /// panic the app.
    #[test]
    fn corrupt_epubs_are_rejected_rather_than_panicking() {
        let tmp = tempfile::tempdir().unwrap();
        let good = std::fs::read(generated_fixture()).unwrap();

        let cases: Vec<(&str, Vec<u8>)> = vec![
            ("empty", Vec::new()),
            ("not a zip", b"this is plainly not a zip archive".to_vec()),
            ("truncated zip", good[..good.len() / 2].to_vec()),
            ("header only", good[..4].to_vec()),
            ("zip with garbage tail", {
                let mut v = good.clone();
                v.extend_from_slice(&[0xde, 0xad, 0xbe, 0xef]);
                v
            }),
            ("nulled central directory", {
                let mut v = good.clone();
                let n = v.len();
                for b in v.iter_mut().skip(n.saturating_sub(64)) {
                    *b = 0;
                }
                v
            }),
        ];

        for (name, bytes) in cases {
            let path = tmp.path().join(format!("{}.epub", name.replace(' ', "-")));
            std::fs::write(&path, &bytes).unwrap();
            // The contract is "does not panic". Either outcome is acceptable —
            // some corruptions still leave a readable OPF.
            let _ = epub_info(&path);
            let _ = extract_cover(&path, &tmp.path().join("images"));
        }
    }

    #[test]
    fn reads_metadata_from_fixture() {
        let Some(path) = optional_fixture() else {
            skip("epubs/pachinko.epub is missing");
            return;
        };
        let info = epub_info(&path).unwrap();
        assert!(info.title.is_some());
        // If an ISBN was found it must be a validated, normalized one.
        if let Some(isbn) = &info.isbn {
            assert!(normalize_isbn(isbn).is_some());
        }
    }

    #[test]
    fn extracts_cover_from_fixture() {
        let Some(path) = optional_fixture() else {
            skip("epubs/pachinko.epub is missing");
            return;
        };
        let dir = std::env::temp_dir().join(format!("rb-epub-test-{}", std::process::id()));
        let cover = extract_cover(&path, &dir).unwrap();
        if let Some(c) = cover {
            assert!(c.exists());
            assert!(std::fs::metadata(&c).unwrap().len() > 0);
        }
        std::fs::remove_dir_all(&dir).ok();
    }
}
