-- GENERATED by `cargo run -p corpus -- gen-synthetic`. Do not hand-edit.
-- `annotations` must win; the legacy `highlight` table is ignored.
return {
    ["annotations"] = {
        [1] = { ["text"] = "from annotations", ["pos0"] = "/body/p[1]/text().0",
                 ["pageno"] = 1, ["datetime"] = "2026-03-01 10:00:00" },
    },
    ["highlight"] = {
        [99] = {
            [1] = { ["text"] = "from legacy highlight", ["pos0"] = "/body/p[99]/text().0",
                     ["datetime"] = "2020-01-01 10:00:00" },
        },
    },
    ["doc_props"] = { ["title"] = "Both Layouts", ["authors"] = "Two Eras" },
}
